image: node:22.8-alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

before_script:
  - corepack enable
  - corepack prepare --activate

  #cache: 
  #  key: $CI_COMMIT_REF_SLUG
  #  paths:
  #    - .pnpm-store
  #  policy: pull-push

pages:
  stage: deploy
  variables:
    VITE_SITE_DESC: "Francesco Calo's blog, a fullstack web developer journey, from devops, automation to functional programming, linux, typescript, nodejs, k8s, bash."
    VITE_PAGE_SIZE: 5
    VITE_SITE: 'https://fracalo.gitlab.io/fcalo-blog-astro/' # 'https://fcalo.com'
  script:
    - pnpm i
    - pnpm build
  artifacts:
    paths:
       - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
