image: node:22.8-alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

before_script:
  - corepack enable
  - corepack prepare --activate

cache: 
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .pnpm-store
  policy: pull-push

pages:
  stage: deploy
  script:
    - pnpm i
    - pnpm build
  artifacts:
    paths:
       - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
