image: node:22.8-alpine

before_script:
  - corepack enable
  - corepack prepare --activate

cache: 
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .pnpm-store
  policy: pull-push

pages:
  script:
    - pnpm i
    - pnpm build
  artifacts:
    paths:
       - dist
