name: GH pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    env:
      VITE_SITE_DESC: "Francesco Calo's blog, a fullstack web developer journey, from devops, automation to functional programming, linux, typescript, nodejs, k8s, bash."
      VITE_PAGE_SIZE: 5
      VITE_SITE: 'https://fcalo.com'
      VITE_SITE_PATH: '/'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - run: pnpm i
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - run: pnpm build 
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
